"""Browser checks run only against integration.py's ephemeral database."""
import json
from pathlib import Path
from playwright.sync_api import sync_playwright, expect

def admin_ui(port,tokens,check):
    origin=f'http://127.0.0.1:{port}'
    with sync_playwright() as p:
        browser=p.chromium.launch(channel='msedge',headless=True)
        context=browser.new_context(viewport={'width':1440,'height':1000})
        page=context.new_page()
        errors=[]
        page.on('pageerror',lambda error:errors.append(str(error)))
        def navigate(key,title):
            page.locator(f'#nav a[href="#{key}"]').click()
            expect(page.locator('#title')).to_have_text(title)
            expect(page.locator('.loading')).to_have_count(0)
            expect(page.locator('#notice')).to_be_hidden()
        def login(role):
            page.locator('#token').fill(tokens[role])
            page.locator('#login-form button').click()
            expect(page.locator('#login')).not_to_be_visible()
            expect(page.locator('.loading')).to_have_count(0)
        page.goto(origin)
        expect(page.locator('#login')).to_be_visible()
        check(page.locator('#content').inner_text().find('token')>=0,'UI data requires login')
        page.locator('#token').fill('0'*64)
        page.locator('#login-form button').click()
        expect(page.locator('#login-error')).not_to_be_empty()
        check(page.locator('#login').is_visible(),'bad UI token rejected')
        login('admin')
        check(page.locator('#role').inner_text()=='Admin','UI recognizes admin role')
        check(page.locator('.stat').count()==4,'dashboard counters rendered')
        check(page.evaluate('localStorage.length===0 && sessionStorage.length===0'),'API token not persisted in browser storage')
        screenshot=Path(__file__).resolve().parents[1]/'.deps/ui-dashboard.png'
        page.screenshot(path=str(screenshot),full_page=True)
        for key,title in [('chargepoints','Stations'),('transactions','Transactions'),('tasks','Command history'),('connectorStatus','Connector status'),('reservations','Reservations'),('reports201','Device reports'),('securityEvents','Security'),('audit','Audit log'),('system','System')]:
            navigate(key,title)
            check(True,'admin UI view '+key)
        navigate('ocppTags','Access & tags')
        page.get_by_label('Id tag',exact=True).fill('<img src=x>')
        page.get_by_label('Max active transactions').fill('0')
        page.get_by_role('button',name='Review & save').click()
        expect(page.locator('#review')).to_be_visible()
        page.locator('#review button[value="confirm"]').click()
        expect(page.locator('.result')).to_contain_text('updated')
        page.locator('#refresh').click()
        expect(page.locator('td').filter(has_text='<img src=x>').first).to_be_visible()
        check(page.locator('img').count()==0,'untrusted station/tag text never becomes HTML')
        page.get_by_role('button',name='Tokens 2.0.1',exact=True).click()
        expect(page.get_by_label('Id token',exact=True)).to_be_visible()
        page.get_by_label('Id token',exact=True).fill('UI_TOKEN')
        page.get_by_label('Group token JSON (optional)',exact=True).fill('{"idToken":"UI_GROUP","type":"Central"}')
        page.get_by_role('button',name='Review & save').click()
        page.locator('#review button[value="confirm"]').click()
        expect(page.locator('.result')).to_contain_text('updated')
        check(True,'UI token provisioning through same-origin authenticated POST')
        token_rows=page.request.get(origin+'/api/v1/idTokens',headers={'Authorization':'Bearer '+tokens['admin']}).json()
        saved=next(row for row in token_rows if row['token']=='UI_TOKEN')
        check(json.loads(saved['group_token_body'])['idToken']=='UI_GROUP','UI persists group token without dropping its association')
        navigate('billing','Billing sandbox')
        page.get_by_role('button',name='Review & simulate settlement').click()
        page.locator('#review button[value="confirm"]').click()
        expect(page.locator('.result')).to_contain_text('"paymentExecuted": false')
        check(True,'UI sandbox settlement persistence')
        navigate('commands','Command center')
        # Every command schema must render its editor without script errors.
        for version in ('1.2','1.5','1.6','2.0.1'):
            page.get_by_label('Protocol',exact=True).select_option(version)
            actions=page.get_by_label('Command',exact=True).locator('option').evaluate_all('(options)=>options.map(o=>o.value)')
            check(len(actions)>0,'UI catalog '+version)
            for action in actions:
                page.get_by_label('Command',exact=True).select_option(action)
                check(page.get_by_role('button',name='Review & send command').is_enabled(),'UI editor '+version+' '+action)
        page.get_by_label('Station',exact=True).select_option('SOAP_16')
        page.get_by_label('Protocol',exact=True).select_option('1.6')
        page.get_by_label('Command',exact=True).select_option('Reset')
        page.get_by_role('button',name='Review & send command').click()
        page.locator('#review button[value="cancel"]').click()
        check('ยังไม่ได้ส่ง' in page.locator('.result').inner_text(),'cancel review never dispatches command')
        page.get_by_role('button',name='Review & send command').click()
        page.locator('#review button[value="confirm"]').click()
        expect(page.locator('.result')).to_contain_text('Accepted')
        check('commandId' in page.locator('.result').inner_text(),'UI command result includes durable correlation ID')
        page.locator('#signout').click()
        login('read')
        check(page.locator('#nav a[href="#commands"]').count()==0,'reader command menu hidden')
        check(page.locator('#nav a[href="#billing"]').count()==0,'reader billing menu hidden')
        page.locator('#signout').click()
        login('operator')
        navigate('commands','Command center')
        page.get_by_label('Protocol',exact=True).select_option('2.0.1')
        page.get_by_label('Command',exact=True).select_option('SetNetworkProfile')
        check(page.get_by_role('button',name='Review & send command').is_disabled(),'operator cannot send admin-only command')
        page.set_viewport_size({'width':390,'height':844})
        page.goto(origin)
        expect(page.locator('#login')).to_be_visible()
        check(page.evaluate('document.documentElement.scrollWidth <= window.innerWidth'),'mobile layout has no horizontal page overflow')
        check(not errors,'browser has no uncaught JavaScript errors: '+str(errors))
        context.close();browser.close()
