#requires -Version 5.1
[CmdletBinding(DefaultParameterSetName = 'Run')]
param(
    [string]$ConfigPath = (Join-Path $PSScriptRoot 'config.local.json'),
    [ValidateSet('Release', 'Debug')][string]$Configuration = 'Release',
    [Parameter(ParameterSetName = 'Init')][switch]$InitConfig,
    [Parameter(ParameterSetName = 'Init')][ValidatePattern('^[A-Za-z0-9_-]{1,64}$')][string]$StationId = 'CP01',
    [Parameter(ParameterSetName = 'Run')][switch]$Build,
    [Parameter(ParameterSetName = 'Run')][switch]$CheckConfig
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$ConfigPath = $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath($ConfigPath)

function New-Secret {
    $bytes = New-Object byte[] 32
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try { $rng.GetBytes($bytes) } finally { $rng.Dispose() }
    return ([BitConverter]::ToString($bytes)).Replace('-', '').ToLowerInvariant()
}

if ($InitConfig) {
    $initial = [ordered]@{
        OCPP_DB_HOST = '127.0.0.1'; OCPP_DB_PORT = 3306
        OCPP_DB_NAME = ''; OCPP_DB_USER = ''; OCPP_DB_PASSWORD = ''; OCPP_DB_CA = ''
        OCPP_PORT = 5003; OCPP_WORKERS = 4
        OCPP_READ_TOKEN = New-Secret; OCPP_OPERATOR_TOKEN = New-Secret; OCPP_ADMIN_TOKEN = New-Secret
        OCPP_STATION_SECRETS = @{ $StationId = (New-Secret) }
    }
    # CreateNew prevents accidentally replacing an existing secret configuration.
    $stream = [System.IO.File]::Open($ConfigPath, [System.IO.FileMode]::CreateNew, [System.IO.FileAccess]::Write)
    try {
        $bytes = (New-Object System.Text.UTF8Encoding($false)).GetBytes(($initial | ConvertTo-Json -Depth 4))
        $stream.Write($bytes, 0, $bytes.Length)
    } finally { $stream.Dispose() }
    Write-Host "Created $ConfigPath"
    Write-Host 'Set OCPP_DB_NAME, OCPP_DB_USER and OCPP_DB_PASSWORD in that file, then run this script again.'
    return
}

if (-not (Test-Path -LiteralPath $ConfigPath -PathType Leaf)) {
    throw 'Configuration file missing. Run this script with -InitConfig first, then fill in database credentials.'
}
try { $config = Get-Content -LiteralPath $ConfigPath -Raw | ConvertFrom-Json }
catch { throw 'Cannot read configuration JSON. Check file permissions and JSON syntax.' }
if ($null -eq $config -or $config -isnot [pscustomobject]) { throw 'Configuration must be a JSON object.' }
$values = [ordered]@{
    OCPP_DB_HOST = '127.0.0.1'; OCPP_DB_PORT = '3306'
    OCPP_DB_NAME = ''; OCPP_DB_USER = ''; OCPP_DB_PASSWORD = ''; OCPP_DB_CA = ''
    OCPP_PORT = '5003'; OCPP_WORKERS = '4'
    OCPP_READ_TOKEN = ''; OCPP_OPERATOR_TOKEN = ''; OCPP_ADMIN_TOKEN = ''; OCPP_STATION_SECRETS = ''
}
foreach ($property in $config.PSObject.Properties) {
    if (-not $values.Contains($property.Name)) { throw 'Unknown configuration key. Use the OCPP_* keys generated by -InitConfig.' }
    if ($property.Name -eq 'OCPP_STATION_SECRETS') {
        if ($property.Value -isnot [pscustomobject]) { throw 'OCPP_STATION_SECRETS must be a JSON object.' }
        $stations = @($property.Value.PSObject.Properties)
        if ($stations.Count -lt 1 -or $stations.Count -gt 10000) { throw 'Configure between 1 and 10000 stations.' }
        $seen = New-Object 'System.Collections.Generic.HashSet[string]'
        foreach ($station in $stations) {
            if ($station.Name -cnotmatch '^[A-Za-z0-9_-]{1,64}$' -or $station.Value -isnot [string] -or
                $station.Value -cnotmatch '^[a-f0-9]{64}$' -or -not $seen.Add($station.Value)) {
                throw 'Each station requires a valid ID and a distinct 64-character lowercase hex secret.'
            }
        }
        $values[$property.Name] = $property.Value | ConvertTo-Json -Compress -Depth 3
        if ([Text.Encoding]::UTF8.GetByteCount($values[$property.Name]) -gt 1048576) { throw 'Station configuration exceeds 1 MiB.' }
    } else {
        if ($null -eq $property.Value -or $property.Value -is [array] -or $property.Value -is [pscustomobject]) {
            throw 'Configuration values must be strings or numbers, except OCPP_STATION_SECRETS.'
        }
        $values[$property.Name] = [string]$property.Value
    }
}
foreach ($name in @('OCPP_DB_NAME', 'OCPP_DB_USER', 'OCPP_DB_PASSWORD', 'OCPP_STATION_SECRETS')) {
    if ([string]::IsNullOrEmpty($values[$name])) { throw "Missing $name in configuration." }
}
$tokens = New-Object 'System.Collections.Generic.HashSet[string]'
foreach ($name in @('OCPP_READ_TOKEN', 'OCPP_OPERATOR_TOKEN', 'OCPP_ADMIN_TOKEN')) {
    if ($values[$name] -cnotmatch '^[a-f0-9]{64}$' -or -not $tokens.Add($values[$name])) {
        throw 'API tokens must be distinct 64-character lowercase hex secrets.'
    }
}
foreach ($name in @('OCPP_PORT', 'OCPP_DB_PORT', 'OCPP_WORKERS')) {
    $maximum = if ($name -eq 'OCPP_WORKERS') { 32 } else { 65535 }
    if ($values[$name] -notmatch '^[0-9]{1,5}$' -or [int]$values[$name] -lt 1 -or [int]$values[$name] -gt $maximum) {
        throw "Invalid $name (allowed: 1-$maximum)."
    }
}
if ([string]::IsNullOrEmpty($values.OCPP_DB_HOST)) { $values.OCPP_DB_HOST = '127.0.0.1' }
if ($values.OCPP_DB_CA) {
    if (-not [IO.Path]::IsPathRooted($values.OCPP_DB_CA)) {
        $values.OCPP_DB_CA = Join-Path (Split-Path -Parent $ConfigPath) $values.OCPP_DB_CA
    }
    if (-not (Test-Path -LiteralPath $values.OCPP_DB_CA -PathType Leaf)) { throw 'OCPP_DB_CA file does not exist.' }
} elseif ($values.OCPP_DB_HOST -cne '127.0.0.1' -and $values.OCPP_DB_HOST -cne 'localhost') {
    throw 'Remote database connections require OCPP_DB_CA.'
}

if ($Build) { & (Join-Path $PSScriptRoot 'scripts/build-windows.ps1') -Configuration $Configuration }
$binaryDirectory = Join-Path $PSScriptRoot "build/$Configuration"
$executable = Join-Path $binaryDirectory 'ocpp_server.exe'
$zlib = if ($Configuration -eq 'Debug') { 'zd.dll' } else { 'z.dll' }
foreach ($name in @('ocpp_server.exe', 'libmariadb.dll', $zlib)) {
    if (-not (Test-Path -LiteralPath (Join-Path $binaryDirectory $name) -PathType Leaf)) {
        throw "Missing build artifact: $name. Run this script with -Build."
    }
}
$schemas = Join-Path $PSScriptRoot 'schemas'
if (-not (Test-Path -LiteralPath (Join-Path $schemas 'Heartbeat.json') -PathType Leaf)) { throw 'OCPP schema files are missing.' }
if ($CheckConfig) {
    Write-Host 'Configuration and runtime files checked. Database connectivity has not been tested.'
    return
}

$saved = @{}
try {
    foreach ($name in $values.Keys) {
        $saved[$name] = [Environment]::GetEnvironmentVariable($name, 'Process')
        [Environment]::SetEnvironmentVariable($name, $values[$name], 'Process')
    }
    Write-Host "Starting OCPP server on http://127.0.0.1:$($values.OCPP_PORT) (Ctrl+C to stop)."
    & $executable $schemas
    if ($LASTEXITCODE -ne 0) { throw "OCPP server exited with code $LASTEXITCODE." }
} finally {
    foreach ($name in $saved.Keys) { [Environment]::SetEnvironmentVariable($name, $saved[$name], 'Process') }
}
