
context.path = develop

# Database configuration

db.schema = ocpptest
db.url = jdbc:mysql://localhost:3306/ocpptest?useSSL=true&serverTimezone=UTC
db.user = barry
db.password = pinkywinky

# CREATE DATABASE ocppdb CHARACTER SET utf8 COLLATE utf8_unicode_ci;
# CREATE USER 'barry'@'localhost' IDENTIFIED BY 'pinkywinky';
# GRANT ALL PRIVILEGES ON ocppdb.* TO 'barry'@'localhost';
# GRANT SELECT ON mysql.proc TO 'barry'@'localhost';
# mvn package

# Credentials for Web interface access
#
auth.user = barry
auth.password = pinkywinky

# The header key and value for Web API access using API key authorization.

webapi.key = OCPP-API-KEY
webapi.value = 12345

# Billing backend API base URL. Keep the trailing slash.
billing.api.base-url = https://localhost:5555/

# Billing database configuration
billing.db.url = jdbc:mysql://localhost:3306/billing?useSSL=false
billing.db.user = blue
billing.db.password = bluestone88

# Jetty configuration
#
server.host = 0.0.0.0
server.gzip.enabled = true

# Jetty HTTP configuration
#
http.enabled = true
http.port = 5002

# Jetty HTTPS configuration
#
https.enabled = false
https.port = 8443
keystore.path =
keystore.password =


ws.session.select.strategy = ALWAYS_LAST


auto.register.unknown.stations = false

### DO NOT MODIFY ###
steve.version = ${project.version}
git.describe = ${git.commit.id.describe}
db.sql.logging = false
profile = prod
