include(FetchContent)
set(BUILD_TESTING OFF CACHE BOOL "Dependency tests" FORCE)
set(JSON_BuildTests OFF CACHE BOOL "" FORCE)
set(JSON_VALIDATOR_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(JSON_VALIDATOR_BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(JSON_VALIDATOR_INSTALL OFF CACHE BOOL "" FORCE)
set(BUILD_CTL OFF CACHE BOOL "" FORCE)
set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE)
set(BUILD_ORM OFF CACHE BOOL "" FORCE)
set(BUILD_BROTLI OFF CACHE BOOL "" FORCE)
set(BUILD_YAML_CONFIG OFF CACHE BOOL "" FORCE)
FetchContent_Declare(json GIT_REPOSITORY https://github.com/nlohmann/json.git GIT_TAG 55f93686c01528224f448c19128836e7df245f72)
FetchContent_Declare(schema_validator GIT_REPOSITORY https://github.com/pboettch/json-schema-validator.git GIT_TAG 349cba9f7e3cb423bbc1811bdd9f6770f520b468)
FetchContent_Declare(drogon GIT_REPOSITORY https://github.com/drogonframework/drogon.git GIT_TAG 4c5430757ea5451a7c38fbbef4b4bef7dbb47f2f GIT_SUBMODULES trantor)
FetchContent_Declare(pugixml GIT_REPOSITORY https://github.com/zeux/pugixml.git GIT_TAG c8033ce9d039e7f9d134877c363397b3cfe20816)
FetchContent_MakeAvailable(json schema_validator drogon pugixml)
include(cmake/harden-drogon.cmake)
find_path(MARIADB_INCLUDE_DIR mysql.h PATH_SUFFIXES mariadb mysql REQUIRED)
find_library(MARIADB_LIBRARY NAMES libmariadb mariadb mariadbclient PATH_SUFFIXES mariadb REQUIRED)

if(NOT WIN32)
  find_package(CURL 7.85 REQUIRED)
  find_package(OpenSSL 3 REQUIRED)
endif()
