function(ocpp_harden target)
  if(MSVC)
    target_compile_options(${target} PRIVATE /W4 /WX /permissive- /utf-8 /sdl /guard:cf)
    target_link_options(${target} PRIVATE /DYNAMICBASE /NXCOMPAT /guard:cf)
  else()
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic -Werror -fstack-protector-strong)
    if(UNIX AND NOT APPLE)
      target_link_options(${target} PRIVATE -Wl,-z,relro,-z,now)
    endif()
    if(OCPP_SANITIZERS)
      target_compile_options(${target} PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
      target_link_options(${target} PRIVATE -fsanitize=address,undefined)
    endif()
  endif()
endfunction()
