<script lang="ts">
 import {onMount} from 'svelte';
 import {api,type Charger,type Event} from '../lib/api';
 import {loadPhysics} from '../lib/physics';
 import './style.css';
 let token=$state(''),connected=$state(false),busy=$state(false),error=$state(''),notice=$state('');
 let chargers=$state<Charger[]>([]),events=$state<Event[]>([]),realEnabled=$state(false),selected=$state('');
 let station=$state('SIM01'),protocol=$state('ocpp1.6'),mode=$state('mock'),capacity=$state(60),soc=$state(20),target=$state(80),power=$state(22),vehicle=$state(11),tag=$state('TEST001');
 let physics=$state<Awaited<ReturnType<typeof loadPhysics>>|null>(null),filter=$state('all');
 let active=$derived(chargers.find(c=>c.id===selected));
 let filtered=$derived(events.filter(e=>(!selected||e.station===selected)&&(filter==='all'||e.type===filter)).slice(-100).reverse());
 let estimate=$derived(physics?physics._sim_estimate_seconds(capacity*1000,soc,target,Math.min(power,vehicle)*1000):-1);
 let reconciled=$state(false);
 $effect(()=>{void selected;reconciled=false;});
 let polling=false;
 async function refresh() {
  if(polling||!connected)return;polling=true;
  try {const [state,log]=await Promise.all([api<{chargers:Charger[];realEnabled:boolean}>(token,'chargers'),api<Event[]>(token,'events')]);chargers=state.chargers;realEnabled=state.realEnabled;events=log;if(!chargers.some(c=>c.id===selected))selected=chargers[0]?.id??'';}
  catch(e){error=String(e instanceof Error?e.message:e);}finally{polling=false;}
 }
 async function login(){busy=true;error='';try {const state=await api<{chargers:Charger[];realEnabled:boolean}>(token,'chargers');chargers=state.chargers;realEnabled=state.realEnabled;connected=true;await refresh();}catch(e){error=String(e instanceof Error?e.message:e);}finally{busy=false;}}
 async function create(){await run(async()=>{await api(token,'chargers',{id:station,protocol,mode,capacityKwh:capacity,soc,targetSoc:target,maxKw:power,vehicleKw:vehicle});selected=station;notice='เพิ่มตู้แล้ว รอ BootNotification';});}
 async function run(task:()=>Promise<void>){busy=true;error='';try{await task();await refresh();}catch(e){error=String(e instanceof Error?e.message:e);}finally{busy=false;}}
 async function action(action:string,extra:Record<string,unknown>={}){if(!active)return;await run(async()=>{await api(token,`chargers/${selected}/actions`,{action,...extra});notice='ส่งคำสั่ง '+action+' แล้ว';});}
 async function scenario(kind:string){if(!active)return;await run(async()=>{
  const send=(action:string,extra:Record<string,unknown>={})=>api(token,`chargers/${selected}/actions`,{action,...extra});
  if(kind==='normal'||kind==='reject'){await send('plug');await send('start',{tag:kind==='reject'?'DENY001':tag});}
  else if(kind==='grid')await send('configure',{gridKw:2,speed:active!.speed});
  else if(kind==='offline')await send('network',{enabled:false});
  else await send('fault',{fault:'EmergencyStop'});
  notice='เริ่มสถานการณ์ '+kind;
 });}
 onMount(()=>{let disposed=false;loadPhysics().then(value=>{if(!disposed)physics=value;}).catch(()=>{notice='โหลด WASM ไม่สำเร็จ: ตัวจำลองบน backend ยังทำงานได้';});const interval=setInterval(refresh,1000);return()=>{disposed=true;clearInterval(interval);};});
</script>
<svelte:head><title>EV Simulation · Charging lab</title><meta name="description" content="EV charger simulation and OCPP protocol workspace"/></svelte:head>
<div class="shell">
 <header><a class="brand" href="/" aria-label="EV Simulation home"><span class="logo">ϟ</span> EV Simulation</a><span class="muted">Charging lab · OCPP 1.6 / 2.0.1</span>{#if connected}<button class="quiet" onclick={()=>{connected=false;token='';chargers=[];events=[];}}>Sign out</button>{/if}</header>
 {#if !connected}
 <main class="welcome"><span class="eyebrow">A WORKSPACE FOR REAL SCENARIOS</span><h1>ทุกสถานการณ์ชาร์จ<br/>ในพื้นที่ทดลองเดียว</h1><p class="intro">จำลองรถ ตู้ชาร์จ และเหตุขัดข้อง พร้อมตรวจข้อความ OCPP ทีละขั้น</p>
 <form class="login panel" onsubmit={e=>{e.preventDefault();login();}}><h2>Connect to your lab</h2><p class="muted">ใช้ admin token จาก <code>simulation/ev_charger/config.local.json</code> หรือไฟล์ runtime บน server</p><label>Workspace token<input type="password" bind:value={token} autocomplete="off" required minlength="64" maxlength="64" placeholder="วาง token 64 ตัวอักษร"/></label><button class="primary" disabled={busy}>Connect →</button><small>Token อยู่ในหน่วยความจำของหน้านี้เท่านั้น</small></form>
 </main>
 {:else}
 <main><div class="title"><div><span class="eyebrow">SIMULATION WORKSPACE</span><h1>Charging lab</h1><p class="muted">พลังงานและสถานะจาก C++ backend · หนึ่ง connector ต่อตู้ · สูงสุด 4 ตู้</p></div><span class="pill">● {chargers.filter(c=>c.online).length} connected</span></div>
 <div class="metrics"><div class="panel"><small>Stations</small><strong>{chargers.length}<em> / 4</em></strong></div><div class="panel"><small>Live power</small><strong>{chargers.reduce((s,c)=>s+c.powerKw,0).toFixed(1)}<em> kW</em></strong></div><div class="panel"><small>Meter total</small><strong>{chargers.reduce((s,c)=>s+c.energyKwh,0).toFixed(3)}<em> kWh</em></strong></div><div class="panel"><small>Transactions</small><strong>{chargers.filter(c=>c.transaction&&c.transaction!=='0').length}</strong></div></div>
 <div class="workspace"><aside><section class="panel"><h2>Stations</h2>{#each chargers as c}<button class:chosen={c.id===selected} class="station" onclick={()=>selected=c.id}><span><b>{c.id}</b><small>{c.protocol} · {c.mode==='mock'?'Mock CSMS':'Real CSMS'}</small></span><span class:green={c.online} class="dot"></span></button>{/each}{#if !chargers.length}<p class="muted">เพิ่มตู้แรกเพื่อเริ่มทดลอง</p>{/if}</section>
 <form class="panel create" onsubmit={e=>{e.preventDefault();create();}}><h2>Add a station</h2><label>Station ID<input bind:value={station} required pattern={'SIM[A-Z0-9_\\-]{1,24}'}/></label><div class="row"><label>Protocol<select bind:value={protocol}><option>ocpp1.6</option><option>ocpp2.0.1</option></select></label><label>Transport<select bind:value={mode}><option value="mock">Mock CSMS</option><option value="real" disabled={!realEnabled}>Real CSMS</option></select></label></div><div class="row"><label>Battery · kWh<input type="number" bind:value={capacity} min="1" max="250" required/></label><label>Initial SoC · %<input type="number" bind:value={soc} min="0" max="99" required/></label></div><div class="row"><label>Target · %<input type="number" bind:value={target} min={soc+0.1} max="100" step="0.1" required/></label><label>Station · kW<input type="number" bind:value={power} min="0.1" max="350" step="0.1" required/></label></div><label>Vehicle acceptance · kW<input type="number" bind:value={vehicle} min="0.1" max="350" step="0.1" required/></label><p class="muted">{physics?'WASM ready':'WASM loading'} · ideal estimate {estimate>0?(estimate/3600).toFixed(1)+' h':'—'} ก่อน taper</p><button class="primary" disabled={busy||chargers.length>=4}>Add station +</button></form></aside>
 <div class="details">{#if active}<section class="panel vehicle"><div class="between"><div><span class="eyebrow">{active.protocol} · {active.mode}</span><h2>{active.id}</h2></div><span class="pill">{active.status}</span></div><div class="battery"><div style:width={active.soc+'%'}></div><span>{active.soc.toFixed(1)}<small>%</small></span></div><div class="row readings"><div><small>Power</small><b>{active.powerKw.toFixed(2)} kW</b></div><div><small>Energy meter</small><b>{active.energyKwh.toFixed(3)} kWh</b></div><div><small>Temperature</small><b>{active.temperature.toFixed(1)} °C</b></div></div><p class="muted">Boot {active.registered?'accepted':'pending'} · transaction {active.transaction||'—'} · queued {active.queued} · {active.speed}× virtual time</p>{#if active.uncertain}<p class="warning">Start acknowledgement lost — ตรวจ transaction บน CSMS ก่อนสร้างตู้ใหม่</p>{/if}
 <div class="controls"><button disabled={busy||active.plugged} onclick={()=>action('plug')}>Plug in</button><button disabled={busy||!active.plugged} onclick={()=>action('unplug')}>Unplug</button><button class="primary" disabled={busy||!active.plugged||!active.registered||active.status==='Charging'||active.status==='Finishing'||active.fault!=='NoError'||active.uncertain||!active.available} onclick={()=>action('start',{tag})}>Start charging</button><button disabled={busy} onclick={()=>action(active.paused?'resume':'pause')}>{active.paused?'Resume':'Pause'}</button><button disabled={busy} onclick={()=>action('stop')}>Stop</button></div>
 <div class="settings"><label>RFID tag<input bind:value={tag} maxlength="20"/></label><label>Grid limit · kW<input type="number" value={active.gridKw} min="0" max="350" step="0.1" onchange={e=>action('configure',{gridKw:Number(e.currentTarget.value)})}/></label><label>Simulation speed<select value={active.speed} onchange={e=>action('configure',{speed:Number(e.currentTarget.value)})}><option value="1">1× real time</option><option value="10">10×</option><option value="60">60×</option></select></label></div>
 <div class="controls"><button onclick={()=>action('network',{enabled:!active!.network})} disabled={busy}>{active.network?'Disconnect network':'Reconnect network'}</button><button onclick={()=>action('availability',{enabled:!active!.available})} disabled={busy}>{active.available?'Set unavailable':'Set available'}</button><button onclick={()=>action('reset')} disabled={busy}>Soft reset</button><button onclick={()=>action('remove',{reconciled})} disabled={busy||(active.uncertain&&!reconciled)}>Remove</button></div>
 </section><section class="panel"><h2>Scenario library</h2><p class="muted">สถานการณ์เริ่มทันทีบนตู้ที่เลือก; ใช้ TEST001 และ DENY001 ใน mock ส่วน real ใช้ tag ที่ CSMS กำหนด</p><div class="scenarios"><button disabled={busy} onclick={()=>scenario('normal')}><b>Normal session</b><small>Plug → authorize → charge</small></button><button disabled={busy} onclick={()=>scenario('reject')}><b>RFID rejected</b><small>Mock tag DENY001</small></button><button disabled={busy} onclick={()=>scenario('grid')}><b>Grid constraint</b><small>Limit power to 2 kW</small></button><button disabled={busy} onclick={()=>scenario('offline')}><b>Network interruption</b><small>Offline meter queue</small></button><button class="danger" disabled={busy} onclick={()=>scenario('emergency')}><b>Emergency stop</b><small>Fault → end transaction</small></button></div><div class="controls"><label>Fault injection<select value={active.fault} onchange={e=>action('fault',{fault:e.currentTarget.value})}><option>NoError</option><option>EmergencyStop</option><option>GroundFailure</option><option>OverTemperature</option><option>PowerLoss</option></select></label></div></section>{:else}<section class="panel empty"><h2>Your lab is ready.</h2><p>เพิ่มตู้ แล้วเลือกสถานการณ์ที่อยากทดสอบ</p></section>{/if}
 <section class="panel trace"><div class="between"><div><h2>Protocol trace</h2><p class="muted">OCPP frames และเหตุการณ์ · เก็บล่าสุด 300 รายการ · แสดงล่าสุด 100 ของตู้ที่เลือก</p></div><select aria-label="Filter events" bind:value={filter}><option value="all">All events</option><option value="out">Outgoing</option><option value="in">Incoming</option><option value="error">Errors</option></select></div>{#each filtered as event (event.sequence)}<details><summary><span class="event-type">{event.type}</span><time>{event.time.slice(11,19)}</time><b>{event.station}</b><span>{Array.isArray(event.message)?typeof event.message[2]==='string'?String(event.message[2]):'CALLRESULT '+JSON.stringify(event.message[2]):typeof event.message==='string'?event.message:JSON.stringify(event.message)}</span></summary><pre>{JSON.stringify(event.message,null,2)}</pre></details>{/each}{#if !filtered.length}<p class="muted">ข้อความ OCPP จะปรากฏหลังเพิ่มตู้</p>{/if}</section>
 </div></div></main>
 {/if}
 {#if error}<div class="toast error" role="alert">{error}<button aria-label="Dismiss error" onclick={()=>error=''}>×</button></div>{:else if notice}<div class="toast" role="status">{notice}<button aria-label="Dismiss notice" onclick={()=>notice=''}>×</button></div>{/if}
 <footer>Virtual EVSE · In-memory lab · ไม่เชื่อมระบบเรียกเก็บเงินจริง · OCPP timestamps ใช้เวลาจริง</footer>
</div>
