'use strict';
const $ = (id) => document.getElementById(id);
const state = {token:'', role:0, session:null, catalog:null, rows:[], offset:0, page:'overview', generation:0, busy:false};
const pages = [
 ['overview','◫','Overview','ภาพรวมการทำงาน',1],['chargepoints','ϟ','Stations','สถานีและการเชื่อมต่อ',1],
 ['transactions','⇄','Transactions','ประวัติธุรกรรม OCPP 1.x และ 2.0.1',1],['commands','⌘','Command center','ส่งคำสั่งและติดตามผลจากสถานี',2],
 ['tasks','◷','Command history','สถานะคำสั่งที่บันทึกไว้',2],['ocppTags','◇','Access & tags','จัดการสิทธิ์ tag และ token',1],
 ['connectorStatus','▤','Connector status','สถานะหัวชาร์จและ EVSE',1],['reservations','▣','Reservations','รายการจองและ charging profiles',1],
 ['reports201','≡','Device reports','รายงานและ device model OCPP 2.0.1',3],['securityEvents','⊙','Security','เหตุการณ์ความปลอดภัยและคำขอใบรับรอง',3],
 ['audit','☷','Audit log','กิจกรรมที่ระบบบันทึก',3],['billing','฿','Billing sandbox','คำนวณทดสอบแยกจากการชำระเงินจริง',3],['system','⚙','System','สถานะและข้อมูลการเชื่อมต่อ',1]
];
function el(tag, text, cls) { const n=document.createElement(tag); if(text!==undefined)n.textContent=text; if(cls)n.className=cls; return n; }
function button(text, fn, cls='secondary') { const b=el('button',text,cls);b.type='button';b.addEventListener('click',fn);return b; }
function showError(error) { $('notice').textContent=error.message||String(error);$('notice').hidden=false; }
function badge(value) { const text=String(value??'—');return el('span',text,'badge '+(/Accepted|Available|Completed|ready|Online|Succeeded|Unlocked/.test(text)?'good':/Failed|Rejected|Faulted|Blocked|Invalid/.test(text)?'bad':/Pending|Uncertain|Unknown|Charging|Offline/.test(text)?'warn':'neutral')); }
function panel(title, body, action) { const p=el('section',undefined,'panel'); const h=el('div',undefined,'panel-head');h.append(el('h2',title));if(action)h.append(action);p.append(h);const b=el('div',undefined,'panel-body');b.append(body);p.append(b);return p; }
function pretty(data) { return JSON.stringify(data,null,2); }
function details(title,data) { $('detail-title').textContent=title;$('detail-body').textContent=pretty(data);$('detail').showModal(); }
function label(text,input,description) { const l=el('label',text);input.setAttribute('aria-label',text);l.append(input);if(description)l.append(el('span',description,'field-description'));return l; }
function input(type='text',value='') { const i=el('input');i.type=type;i.value=value;return i; }
function select(options,value) { const s=el('select');for(const [v,t] of options)s.append(new Option(t,v));if(value!==undefined)s.value=value;return s; }
async function request(path, body) {
 const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),40000);
 try { const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:{'Authorization':'Bearer '+state.token,...(body===undefined?{}:{'Content-Type':'application/json'})},body:body===undefined?undefined:JSON.stringify(body),signal:controller.signal,cache:'no-store',credentials:'omit'});
 const data=await r.json();if(!r.ok){if(r.status===401&&state.token){const e=new Error('สิทธิ์ไม่เพียงพอหรือ token ไม่ถูกต้อง (HTTP 401)');e.status=r.status;throw e;}const e=new Error((data.error||'Request failed')+' (HTTP '+r.status+')');e.commandId=r.headers.get('X-OCPP-Command-ID');throw e;}
 return {data,commandId:r.headers.get('X-OCPP-Command-ID')};
 } catch(e) { if(e.name==='AbortError')throw new Error('หมดเวลารอผล ตรวจ Command history ก่อนส่งซ้ำ');throw e; } finally {clearTimeout(timer);}
}
async function get(resource,offset=0) { return (await request('/api/v1/'+resource+'?offset='+offset)).data; }
async function health() { try {const r=await fetch('/health/ready',{cache:'no-store'});const d=await r.json();$('health').textContent=r.ok&&d.status==='ready'?'DB ready':'DB unavailable';$('health').className='badge '+(r.ok?'good':'bad');}catch{ $('health').textContent='Server unreachable';$('health').className='badge bad';} }
function navIcon(id) {
 const paths={overview:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',chargepoints:'M13 2 5 13h6l-1 9 9-13h-7z',transactions:'M4 7h16m-4-4 4 4-4 4 M20 17H4m4-4-4 4 4 4',commands:'M4 5h16v14H4z M8 9l3 3-3 3 M13 15h3',tasks:'M3 12a9 9 0 1 0 3-7 M3 3v5h5 M12 7v5l3 2',ocppTags:'M3 3h8l10 10-8 8L3 11z M7 7h.01',connectorStatus:'M8 3v5m8-5v5 M5 8h14v3a7 7 0 0 1-14 0z M12 18v4',reservations:'M5 4h14v17H5z M8 2v4m8-4v4 M5 9h14 M8 13h3m2 0h3 M8 17h3',reports201:'M5 3h10l4 4v14H5z M14 3v5h5 M8 12h8m-8 4h8',securityEvents:'M12 2 3 6v6c0 5 9 10 9 10s9-5 9-10V6z M8 12l3 3 5-6',audit:'M8 5h12M8 12h12M8 19h12 M3 5h.01M3 12h.01M3 19h.01',billing:'M4 4h16v16H4z M4 9h16 M8 14h.01m4 0h4',system:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M10 2h4l1 3 3 1 3-1 2 4-2 2v3l2 2-2 4-3-1-3 1-1 3h-4l-1-3-3-1-3 1-2-4 2-2v-3L1 9l2-4 3 1 3-1z'};
 const span=el('span',undefined,'nav-icon');span.setAttribute('aria-hidden','true');const svg=document.createElementNS('http://www.w3.org/2000/svg','svg');svg.setAttribute('viewBox','0 0 24 24');svg.setAttribute('fill','none');svg.setAttribute('stroke','currentColor');svg.setAttribute('stroke-width','1.5');svg.setAttribute('stroke-linecap','round');svg.setAttribute('stroke-linejoin','round');const path=document.createElementNS(svg.namespaceURI,'path');path.setAttribute('d',paths[id]||paths.overview);svg.append(path);span.append(svg);return span;
}
function nav() { $('nav').replaceChildren();for(const [id,,title,,role] of pages){if(state.role<role)continue;if(id==='overview'||id==='reports201')$('nav').append(el('div',id==='overview'?'OPERATIONS':'ADMINISTRATION','nav-group'));const a=el('a');a.href='#'+id;a.append(navIcon(id),el('span',title));if(state.page===id){a.className='active';a.setAttribute('aria-current','page');}$('nav').append(a);} }
function logout() {state.token='';state.role=0;state.session=null;state.catalog=null;state.rows=[];state.generation++;$('role').textContent='Not signed in';$('signout').hidden=true;$('content').replaceChildren(el('div','กรอก token เพื่อเริ่มใช้งาน','empty'));$('notice').hidden=true;nav();$('token').value='';$('login-error').textContent='';if(!$('login').open)$('login').showModal();}
async function review(title,description,payload) {if($('review').open)return false;$('review-title').textContent=title;$('review-description').textContent=description;$('review-payload').textContent=pretty(payload);return new Promise(resolve=>{$('review').returnValue='cancel';$('review').addEventListener('close',()=>resolve($('review').returnValue==='confirm'),{once:true});$('review').showModal();});}
async function write(path,payload,title,description,result) {
 if(state.busy)return;state.busy=true;
 try {if(!await review(title,description,payload))return;result.textContent='กำลังส่ง…';const r=await request(path,payload);result.textContent=pretty(r.commandId?{commandId:r.commandId,response:r.data}:r.data);await health();}
 catch(e){result.textContent=(e.commandId?'Command ID: '+e.commandId+'\n':'')+e.message;showError(e);}finally{state.busy=false;}
}
const names={charge_box_id:'Station',station_id:'Station',registration_status:'Registration',ocpp_protocol:'Protocol',charge_point_vendor:'Vendor',charge_point_model:'Model',last_heartbeat_timestamp:'Last heartbeat',transaction_pk:'Transaction',transaction_id:'Transaction',id_tag:'Tag',start_timestamp:'Started',end_timestamp:'Ended',start_value:'Meter start',connector_id:'Connector',status_timestamp:'Recorded',error_code:'Error',command_id:'Command ID',action:'Action',state:'State',created_at:'Created',completed_at:'Completed',max_active_transaction_count:'Session limit',expiry_date:'Expiry',token:'Token',token_type:'Type',status:'Status',evse_id:'EVSE'};
function format(value) {if(value===null||value===undefined)return '—';if(typeof value==='object')return JSON.stringify(value);return String(value);}
function csv(rows) { const cols=[...new Set(rows.flatMap(Object.keys))];const q=x=>'"'+format(x).replaceAll('"','""').replace(/^[=+@-]/,"'$&")+'"';const text='\ufeff'+[cols.map(q).join(','),...rows.map(r=>cols.map(k=>q(r[k])).join(','))].join('\r\n');const url=URL.createObjectURL(new Blob([text],{type:'text/csv;charset=utf-8'}));const a=el('a');a.href=url;a.download=state.page+'-page-'+state.offset+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); }
function dataTable(rows,columns,actions=true) {
 const wrap=el('div',undefined,'table-wrap');if(!rows.length){const empty=el('div',undefined,'empty');empty.append(el('strong','ยังไม่มีรายการ'),el('span','ข้อมูลจะแสดงเมื่อระบบได้รับหรือบันทึกรายการ'));wrap.append(empty);return wrap;}
 const table=el('table');const head=el('tr');for(const k of columns)head.append(el('th',names[k]||k));if(actions)head.append(el('th','Details'));const thead=el('thead');thead.append(head);table.append(thead);const tbody=el('tbody');
 for(const row of rows){const tr=el('tr');for(const k of columns){const td=el('td');const v=row[k];if(/status|state|connection/.test(k))td.append(badge(v));else{td.textContent=format(v);td.title=format(v);}tr.append(td);}if(actions){const td=el('td');td.append(button('View',()=>details('Record details',row),'row-button'));tr.append(td);}tbody.append(tr);}table.append(tbody);wrap.append(table);return wrap;
}
function grid(rows,resource,columns,extraAction) {
 state.rows=rows;const block=el('div');const toolbar=el('div',undefined,'toolbar');const search=input('search');search.placeholder='ค้นหาในหน้านี้…';search.setAttribute('aria-label','Search current page');toolbar.append(search,button('Export this page',()=>csv(filtered)));if(extraAction)toolbar.append(extraAction);block.append(toolbar);const p=el('section',undefined,'panel');const holder=el('div');p.append(holder);let filtered=rows;
 const paint=()=>{const term=search.value.toLowerCase();filtered=rows.filter(r=>JSON.stringify(r).toLowerCase().includes(term));holder.replaceChildren(dataTable(filtered,columns||Object.keys(rows[0]||{}).slice(0,7)));};search.addEventListener('input',paint);paint();
 const pager=el('div',undefined,'pager');pager.append(el('span',`Offset ${state.offset} • ${rows.length} rows (100 per page)`));const controls=el('div');const prev=button('← Previous',()=>{state.offset=Math.max(0,state.offset-100);render();});prev.disabled=state.offset===0;const next=button('Next →',()=>{state.offset+=100;render();});next.disabled=rows.length<100;controls.append(prev,next);pager.append(controls);p.append(pager);block.append(p);if(resource==='chargepoints'){holder.replaceChildren();paint();const note=el('p','Online หมายถึงมี WebSocket session อยู่ตอนโหลดหน้านี้ ส่วน SOAP แสดงตาม endpoint ที่ตั้งค่าไว้','hint');block.append(note);}return block;
}
function tabs(items,selected,changed) {const t=el('div',undefined,'tabs');for(const [key,text] of items){const b=button(text,()=>changed(key));if(key===selected)b.classList.add('active');t.append(b);}return t;}
let subpage={transactions:'transactions',connectorStatus:'connectorStatus',reservations:'reservations',reports201:'reports201',securityEvents:'securityEvents',ocppTags:'ocppTags',billing:'calculator'};
const tabSets={transactions:[['transactions','OCPP 1.x'],['transactions201','OCPP 2.0.1']],connectorStatus:[['connectorStatus','Connectors 1.x'],['evseStatus201','EVSE 2.0.1']],reservations:[['reservations','Reservations 1.x'],['reservations201','Reservations 2.0.1'],['profiles201','Profiles 2.0.1']],reports201:[['reports201','Report chunks'],['deviceModel201','Device model'],['stations201','Station metadata']],securityEvents:[['securityEvents','Security events'],['certificateRequests','CSR requests']],ocppTags:[['ocppTags','Tags 1.x'],['idTokens','Tokens 2.0.1']],billing:[['calculator','Settlement calculator'],['billingSandbox','Simulation ledger']]};
async function overview(content,generation) {
 const [metrics,stations,audit]=await Promise.all([get('metrics'),get('chargepoints'),state.role===3?get('audit'):Promise.resolve([])]);if(generation!==state.generation)return;
 const stats=el('div',undefined,'stats');for(const [title,value,note] of [['Connected stations',metrics.sessions,'Live WebSocket sessions'],['Stations on this page',stations.length,'First 100 registered stations'],['Frames received',metrics.frames,'Since this process started'],['Protocol errors',metrics.errors,'Since this process started']]){const s=el('div',undefined,'stat');s.append(el('div',title,'stat-label'),el('strong',String(value)),el('small',note));stats.append(s);}content.append(stats);
 const enriched=stationRows(stations);const stationPanel=panel('Station fleet',dataTable(enriched,['charge_box_id','connection','registration_status','ocpp_protocol','last_heartbeat_timestamp']),button('All stations →',()=>location.hash='chargepoints'));content.append(stationPanel);
 const col=el('div',undefined,'two-column');const activity=el('div');for(const row of audit.slice(0,5)){const item=el('div',undefined,'activity');item.append(badge(row.action));const d=el('div');d.append(el('h3',row.station_id||'System'),el('small',row.created_at));item.append(d);activity.append(item);}if(!audit.length)activity.append(el('p',state.role===3?'ยังไม่มี audit activity':'Audit activity ต้องใช้สิทธิ์ admin'));col.append(panel('Recent activity',activity));const quick=el('div',undefined,'stack');quick.append(el('p','ใช้ Command center ส่งคำสั่งตาม protocol ของสถานี พร้อมตรวจผลใน Command history'));if(state.role>=2)quick.append(button('Open command center →',()=>location.hash='commands','primary'));quick.append(button('Connection details',()=>location.hash='system'));col.append(panel('Operations desk',quick));content.append(col);
}
function stationRows(rows) {const online=new Map(state.session.onlineStations.map(s=>[s.station,s.protocol]));return rows.map(r=>({...r,connection:online.has(r.charge_box_id)?'Online':state.session.soapStations.includes(r.charge_box_id)?'SOAP configured':'Offline',ocpp_protocol:online.get(r.charge_box_id)||r.ocpp_protocol}));}
function tagForm(row={},token201=false) {
 const f=el('form',undefined,'grid-form'),result=el('pre','พร้อมบันทึก','result');const id=input('text',row.id_tag||row.token||'');id.required=true;id.maxLength=token201?36:20;
 const type=select(['Central','eMAID','ISO14443','ISO15693','KeyCode','Local','MacAddress','NoAuthorization'].map(x=>[x,x]),row.token_type||'Central');const status=select(['Accepted','Blocked','ConcurrentTx','Expired','Invalid','NoCredit','NotAllowedTypeEVSE','NotAtThisLocation','NotAtThisTime','Unknown'].map(x=>[x,x]),row.status||'Accepted');
 const max=input('number',row.max_active_transaction_count??1);max.min=-1;max.max=1000;max.required=true;const expiry=input('text',row.expiry_date?String(row.expiry_date).replace(' ','T')+'Z':row.expiry_timestamp?String(row.expiry_timestamp).replace(' ','T')+'Z':'');expiry.placeholder='2026-12-31T23:59:59Z';const parent=input('text',row.parent_id_tag||'');parent.maxLength=20;
 const group=el('textarea');group.value=row.group_token_body||'';group.placeholder='{"idToken":"GROUP_ID","type":"Central"}';
 f.append(label(token201?'Id token':'Id tag',id));if(token201)f.append(label('Token type',type),label('Authorization status',status),label('Group token JSON (optional)',group));else f.append(label('Max active transactions',max,'0 = blocked, -1 = unlimited'),label('Parent tag (optional)',parent));f.append(label('Expiry in UTC (optional)',expiry));const save=el('button','Review & save','primary');save.type='submit';f.append(save);
 f.addEventListener('submit',async e=>{e.preventDefault();try{const p=token201?{idToken:{idToken:id.value,type:type.value},idTokenInfo:{status:status.value,...(expiry.value?{cacheExpiryDateTime:expiry.value}:{}),...(group.value?{groupIdToken:JSON.parse(group.value)}:{})}}:{idTag:id.value,maxActiveTransactions:Number(max.value),...(parent.value?{parentIdTag:parent.value}:{}),...(expiry.value?{expiryDate:expiry.value}:{})};await write('/api/v1/'+(token201?'idTokens':'ocppTags'),p,'Save access record','ข้อมูลนี้จะอัปเดตสิทธิ์การชาร์จในฐานข้อมูล',result);}catch(err){showError(err);}});const body=el('div');body.append(f,result);return panel(token201?'Create / update token':'Create / update tag',body);
}
async function records(content,generation) {
 const page=state.page;const tabList=tabSets[page];const resource=subpage[page]||page;if(tabList){const visible=tabList.filter(([r])=>r!=='idTokens'||state.role===3);content.append(tabs(visible,resource,r=>{subpage[page]=r;state.offset=0;render();}));}
 if(resource==='calculator'){billing(content);return;}
 let rows=await get(resource,state.offset);if(generation!==state.generation)return;if(resource==='chargepoints')rows=stationRows(rows);
 const columns=resource==='chargepoints'?['charge_box_id','connection','registration_status','ocpp_protocol','charge_point_vendor','last_heartbeat_timestamp']:resource==='transactions'?['transaction_pk','charge_box_id','id_tag','state','start_timestamp','stop_timestamp','stop_value']:undefined;
 const action=resource==='chargepoints'&&state.role===3?button('Register station',()=>provision(content),'primary'):null;content.append(grid(rows,resource,columns,action));
 if(resource==='chargepoints'){
  const f=el('form',undefined,'toolbar'),id=input();id.placeholder='Station ID, e.g. CP01';id.required=true;const go=el('button','Read station state','secondary');go.type='submit';f.append(id,go);f.addEventListener('submit',async e=>{e.preventDefault();try{details('Station state • '+id.value,(await request('/api/v1/chargepoints/'+encodeURIComponent(id.value)+'/state')).data);}catch(err){showError(err);}});content.append(panel('Station state',f));
 }
 if((resource==='ocppTags'||resource==='idTokens')&&state.role===3){const editor=el('div');editor.append(tagForm({},resource==='idTokens'));const choose=select([['','Select existing record to edit'],...rows.map((r,i)=>[String(i),r.id_tag||r.token])]);choose.addEventListener('change',()=>editor.replaceChildren(tagForm(choose.value===''?{}:rows[Number(choose.value)],resource==='idTokens')));content.append(label('Edit an existing record',choose),editor);}
 if(resource==='tasks'){const f=el('form',undefined,'toolbar'),id=input();id.required=true;id.placeholder='Command ID';const go=el('button','Read command result','secondary');go.type='submit';f.append(id,go);f.addEventListener('submit',async e=>{e.preventDefault();try{details('Command '+id.value,(await request('/api/v1/tasks/'+encodeURIComponent(id.value))).data);}catch(err){showError(err);}});content.append(panel('Inspect command',f),el('p','Uncertain หมายถึงยืนยันผลไม่ได้ ตรวจสถานีจริงก่อนส่งคำสั่งซ้ำ','hint'));}
 if(resource==='certificateRequests')content.append(el('p','CSR ที่รับไว้รอการตรวจจาก issuer การออกใบรับรองอัตโนมัติยังไม่ได้เชื่อม provider','hint'));
 if(resource==='reports201')content.append(el('p','แสดง report chunks ที่ได้รับ การรวมรายงานและตรวจว่าครบทุก chunk ยังอยู่ระหว่างพัฒนา','hint'));
}
function provision(content) {if($('provision-form')){$('provision-form').scrollIntoView();return;}const f=el('form'),id=select(state.session.configuredStations.map(s=>[s,s]));id.required=true;f.id='provision-form';f.append(label('Station with configured credentials',id),el('p','เพิ่ม station ID ใหม่ใน config.local.json และ restart server ก่อน จึงจะเลือกลงทะเบียนได้','hint'));const b=el('button','Review registration','primary');b.type='submit';f.append(b);const result=el('pre','', 'result');f.addEventListener('submit',async e=>{e.preventDefault();await write('/api/v1/chargepoints',{chargeBoxId:id.value},'Register '+id.value,'ลงทะเบียนสถานีที่มี credentials ตั้งค่าไว้แล้ว',result);});content.append(panel('Register station',f),result);f.scrollIntoView({behavior:'smooth'});}
function resolveSchema(schema,root) {if(!schema.$ref)return schema;return schema.$ref.split('/').slice(1).reduce((o,k)=>o[k],root);}
function sample(schema,root) {const s=resolveSchema(schema,root);if(s.enum)return s.enum[0];if(s.type==='object'){const o={};for(const k of s.required||[])o[k]=sample(s.properties[k],root);return o;}if(s.type==='array')return Array.from({length:Math.max(1,s.minItems||0)},()=>sample(s.items,root));if(s.type==='boolean')return false;if(s.type==='integer'||s.type==='number')return s.minimum??0;if(s.format==='date-time')return new Date().toISOString();return '';}
function schemaFields(root,holder,initial) {
 holder.replaceChildren();const fields=[];
 for(const [key,original] of Object.entries(root.properties||{})){if(key==='customData')continue;const s=resolveSchema(original,root);const required=(root.required||[]).includes(key);let field;
 if(s.enum)field=select([...(required?[]:[['','— optional —']]),...s.enum.map(x=>[String(x),String(x)])],initial[key]);
 else if(s.type==='object'||s.type==='array'){field=el('textarea');field.placeholder=pretty(sample(s,root));field.value=initial[key]===undefined?'':pretty(initial[key]);}
 else if(s.type==='boolean')field=select([...(required?[]:[['','— optional —']]),['false','false'],['true','true']],String(initial[key]??false));
 else{field=input(s.type==='integer'||s.type==='number'?'number':'text',initial[key]??'');if(s.type==='integer')field.step='1';if(s.type==='number')field.step='any';if(s.minimum!==undefined)field.min=s.minimum;if(s.maximum!==undefined)field.max=s.maximum;if(s.maxLength)field.maxLength=s.maxLength;}
 field.required=required;const l=label(key+(required?' *':''),field,(s.description||'').replaceAll('\\r\\n',' ').slice(0,220));if(s.type==='array'||s.type==='object')l.className='full';holder.append(l);fields.push([key,s,field]);
 }
 return ()=>{const p={};for(const [key,s,f]of fields){if(!f.value&&!f.required)continue;if(s.type==='array'||s.type==='object')p[key]=JSON.parse(f.value);else if(s.type==='boolean')p[key]=f.value==='true';else if(s.type==='integer'||s.type==='number')p[key]=Number(f.value);else p[key]=f.value;}return p;};
}
async function commands(content,generation) {
 const stations=await get('chargepoints');if(generation!==state.generation)return;const station=select([['','Select station'],...stations.map(s=>[s.charge_box_id,s.charge_box_id])]);station.required=true;const version=select(['1.2','1.5','1.6','2.0.1'].map(v=>[v,'OCPP '+v]),'1.6'),action=select([]);action.required=true;
 const body=el('div'),form=el('form'),top=el('div',undefined,'grid-form');top.append(label('Station',station),label('Protocol',version),label('Command',action));form.append(top);const connection=el('p','เลือกสถานีเพื่อดูสถานะการเชื่อมต่อ','hint');form.append(connection);
 const mode=select([['form','Form fields'],['json','Advanced JSON']]);form.append(label('Payload editor',mode));const fields=el('div',undefined,'grid-form'),json=el('textarea');json.rows=14;json.hidden=true;json.setAttribute('aria-label','Command JSON payload');const schemaButton=button('View schema',()=>{if(entry)details(action.value+' schema',entry.schema);});form.append(fields,json,schemaButton);const hint=el('p','', 'hint');form.append(hint);const send=el('button','Review & send command →','primary');send.type='submit';form.append(send);const result=el('pre','ยังไม่ได้ส่งคำสั่ง','result');let entry=null,readFields=()=>({});
 const rebuild=()=>{entry=(state.catalog[version.value]||[]).find(e=>e.action===action.value);if(!entry)return;const initial=sample(entry.schema,entry.schema);json.value=pretty(initial);readFields=schemaFields(entry.schema,fields,initial);send.disabled=entry.requiredRole>state.role;hint.textContent=send.disabled?'คำสั่งนี้ต้องใช้สิทธิ์ admin':'คำสั่งจะส่งไปยัง station ที่เลือกและบันทึก task เมื่อเริ่ม dispatch • ระวังคำสั่ง Reset, Stop และ firmware';};
 const actions=()=>{action.replaceChildren();for(const e of [...(state.catalog[version.value]||[])].sort((a,b)=>a.action.localeCompare(b.action)))action.append(new Option(e.action,e.action));rebuild();};version.addEventListener('change',actions);action.addEventListener('change',rebuild);actions();
 mode.addEventListener('change',()=>{fields.hidden=mode.value==='json';json.hidden=mode.value!=='json';if(mode.value==='json'){try{json.value=pretty(readFields());}catch(e){showError(e);}}else{try{readFields=schemaFields(entry.schema,fields,JSON.parse(json.value));}catch(e){showError(e);}}});
 station.addEventListener('change',()=>{const online=state.session.onlineStations.find(s=>s.station===station.value);const stored=stations.find(s=>s.charge_box_id===station.value);const v=online?.protocol.replace('ocpp','')||stored?.ocpp_protocol?.replace('ocpp','');if(state.catalog[v]){version.value=v;actions();}connection.textContent=online?'Online • '+online.protocol:state.session.soapStations.includes(station.value)?'SOAP endpoint configured':'Offline • คำสั่งจะถูกปฏิเสธหากไม่มี WebSocket หรือ SOAP endpoint';});
 form.addEventListener('submit',async e=>{e.preventDefault();try{const p=mode.value==='json'?JSON.parse(json.value):readFields();await write('/api/v1/chargepoints/'+encodeURIComponent(station.value)+'/commands/'+encodeURIComponent(action.value),p,action.value+' → '+station.value,'ตรวจ station, protocol และ payload ก่อนส่ง คำสั่งบางชนิดกระทบการชาร์จจริง',result);}catch(err){showError(err);}});body.append(form);content.append(panel('Dispatch a command',body),panel('Station response',result));
}
function billing(content) {
 content.append(el('div','SANDBOX • บันทึกผลจำลองใน DB แยก ไม่มีการเรียก payment gateway หรือส่งคำสั่งหยุดชาร์จ','section-note'));
 const f=el('form',undefined,'grid-form');const fields={caseId:input('text','SIM_'+Date.now()),paidMinor:input('number','1000'),pricePerKwhMinor:input('number','800'),parkingPerMinuteMinor:input('number','20'),parkingGraceSeconds:input('number','60'),start:input('text','10000'),stop:input('text','11000'),ended:input('text',new Date().toISOString()),departed:input('text',new Date().toISOString())};
 for(const [k,title]of [['caseId','Case ID'],['paidMinor','Paid (minor THB)'],['pricePerKwhMinor','Price / kWh (minor THB)'],['parkingPerMinuteMinor','Parking / minute (minor THB)'],['parkingGraceSeconds','Parking grace (seconds)'],['start','Meter start (Wh)'],['stop','Meter stop (Wh)'],['ended','Charge ended (UTC)'],['departed','Departed (UTC)']]){fields[k].required=true;if(fields[k].type==='number'){fields[k].min='0';fields[k].step='1';}f.append(label(title,fields[k]));}
 const b=el('button','Review & simulate settlement','primary');b.type='submit';f.append(b);const result=el('pre','100 minor THB = 1 บาท • ค่าไฟและค่าจอดปัดตามกติกา sandbox','result');f.addEventListener('submit',async e=>{e.preventDefault();const p={caseId:fields.caseId.value,currency:'THB',paidMinor:Number(fields.paidMinor.value),pricePerKwhMinor:Number(fields.pricePerKwhMinor.value),parkingPerMinuteMinor:Number(fields.parkingPerMinuteMinor.value),parkingGraceSeconds:Number(fields.parkingGraceSeconds.value),meterStart:{value:fields.start.value,unit:'Wh'},meterStop:{value:fields.stop.value,unit:'Wh'},chargeEndedAt:fields.ended.value,departedAt:fields.departed.value};await write('/api/v1/billing/sandbox/settle',p,'Record sandbox settlement','บันทึก case จำลอง กรอก case ID เดิมและข้อมูลเดิมจะคืนผลเดิม',result);});content.append(panel('Settlement calculator',f),panel('Simulation result',result));
}
async function system(content,generation) {const metrics=await get('metrics');if(generation!==state.generation)return;const info=el('div');info.append(el('p','HTTP origin: '+location.origin),el('p','OCPP WebSocket: '+location.origin.replace(/^http/,'ws')+'/ocpp/{stationId}'),el('p','Protocols: ocpp1.2 • ocpp1.5 • ocpp1.6 • ocpp2.0.1'),el('p','สิทธิ์ปัจจุบัน: '+['','Reader','Operator','Admin'][state.role]));content.append(panel('Runtime counters',dataTable([metrics],Object.keys(metrics),false)),panel('Connection information',info));const note=el('div',undefined,'stack');note.append(el('p','จัดการ station secrets, API tokens, transfer origins และ SOAP endpoints ผ่าน config.local.json แล้ว restart server'),el('p','UI นี้ดูแลความสามารถที่ backend มีแล้ว ส่วนการออกใบรับรอง, payment gateway, fleet optimizer และหน้าเดิมบางส่วนยังไม่ได้ย้ายครบ'));content.append(panel('Configuration & scope',note));}
async function render() {
 if(!state.token)return;state.page=location.hash.slice(1)||'overview';const page=pages.find(p=>p[0]===state.page&&p[4]<=state.role);if(!page){location.hash='overview';return;}
 const generation=++state.generation;nav();$('title').textContent=page[2];$('crumb').textContent=page[2];$('subtitle').textContent=page[3];$('notice').hidden=true;const content=$('content');content.replaceChildren(el('div','Loading workspace…','loading'));
 try {state.session=(await request('/api/v1/admin/session')).data;if(generation!==state.generation)return;const target=el('div');if(state.page==='overview')await overview(target,generation);else if(state.page==='commands')await commands(target,generation);else if(state.page==='system')await system(target,generation);else await records(target,generation);if(generation===state.generation)content.replaceChildren(target);}catch(e){if(generation===state.generation){content.replaceChildren(el('div','โหลดข้อมูลไม่สำเร็จ กด Refresh เพื่อลองใหม่','empty'));showError(e);}}health();
}
$('login-form').addEventListener('submit',async e=>{e.preventDefault();const b=e.target.querySelector('button');b.disabled=true;$('login-error').textContent='';state.token=$('token').value.trim();try{state.session=(await request('/api/v1/admin/session')).data;state.role=state.session.role;state.catalog=(await request('/api/v1/admin/commands')).data;$('role').textContent=['','Reader','Operator','Admin'][state.role];$('signout').hidden=false;$('token').value='';$('login').close();await render();}catch(err){state.token='';state.role=0;$('login-error').textContent=err.message;}finally{b.disabled=false;}});
$('login').addEventListener('cancel',e=>e.preventDefault());$('signout').addEventListener('click',logout);$('detail-close').addEventListener('click',()=>$('detail').close());$('refresh').addEventListener('click',render);window.addEventListener('hashchange',()=>{state.offset=0;render();});logout();health();
